// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwuqjfzndoywylmldhcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3dXFqZnpuZG95d3lsbWxkaGNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NDgwMDYsImV4cCI6MjA2NjQyNDAwNn0.gY6Hvu8LT54zx4i_THtqmR2znbOu8WAaEjocLTJnL-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);